services:
  postgresql:
    image: postgresql-db
    deploy:
        replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "max_connections=170"]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - project-management-system-network

  service-discovery:
    image: service-discovery-1.0
    deploy:
      replicas: 1
    ports:
      - "8761:8761"
    networks:
      - project-management-system-network

  config-server:
    image: config-server-1.0
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    networks:
      - project-management-system-network

  api-gateway:
    image: api-gateway-1.0
    deploy:
      replicas: 1
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - target: 8762
        published: 8762
        protocol: tcp
        mode: host
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar api-gateway-1.0.jar
    networks:
      - project-management-system-network

  auth-service:
    image: auth-service-1.0
    deploy:
      replicas: 3
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar auth-service-1.0.jar
    networks:
      - project-management-system-network

  user-service:
    image: user-service-1.0
    deploy:
      replicas: 3
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar user-service-1.0.jar
    networks:
      - project-management-system-network

  project-service:
    image: project-service-1.0
    deploy:
      replicas: 3
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar project-service-1.0.jar
    networks:
      - project-management-system-network

  task-service:
    image: task-service-1.0
    deploy:
      replicas: 3
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar task-service-1.0.jar
    networks:
      - project-management-system-network

  ai-service:
    image: ai-service-1.0
    deploy:
      replicas: 3
    environment:
      CONFIG_SERVER_HOST: config-server
      SPRING_PROFILES_ACTIVE: docker
    entrypoint: ../wait-for-it.sh config-server:8888 --timeout=20 -- java -jar ai-service-1.0.jar
    networks:
      - project-management-system-network

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    deploy:
      replicas: 1
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - project-management-system-network

networks:
  project-management-system-network:
    driver: overlay

volumes:
  pgdata: