pipeline {
    agent any
    tools {
        jdk 'java-21-openjdk-amd64'
    }
    stages {
        stage("Clone the project from GitHub") {
            steps {
                git branch: 'master', url: 'https://github.com/skovdev/project-management-system.git'
            }
        }
        stage("Compilation") {
            steps {
                withMaven(jdk: 'jdk-20', maven: 'apache-maven-3.9.3') {
                    sh "mvn clean install -DskipTests"
                }
            }
        }
        stage("Tests") {
            steps {
                withMaven(jdk: 'jdk-20', maven: 'apache-maven-3.9.3') {
                    sh "mvn test"
                }
            }
        }
    }
}
